### PR TITLE
Python3 update for dot2tex

### PR DESCRIPTION
**Pull request by tscrim**
I have gone through dot2tex and made it ready so that it passes all tests (except for the semicolon test, see #5) for both Python2 and Python3.

A big thank you to the initial work done by @Naereen, which formed the base of these changes.

### CODE REVIEW

**Comment by tscrim** [comment]
The only thing that will need to be tweaked is what the version number will be on this merge.

**Comment by tscrim** [comment]
This also drops support for Python versions below 2.7 (as I use the `OrderedDict` class).

**Comment by kjellmf** [comment]
Thank you for the pull request. Its been a long time since I worked on dot2tex, so I need a few days to revive my development environment and test things before I can merge.

I'm fine with dropping 2.7 support, so the dot2tex version number should probably be bumped to 3.0.0

**Comment by tscrim** [comment]
> Thank you for the pull request. Its been a long time since I worked on dot2tex, so I need a few days to revive my development environment and test things before I can merge.

Thank you for taking the time to merge these in and keep this project alive. dot2tex (via SageMath) has been essential for my mathematics research.

> I'm fine with dropping 2.7 support, so the dot2tex version number should probably be bumped to 3.0.0

I still kept support for 2.7, but anything below (specifically 2.6) is dropped because it does not have the `OrderedDict` class.

**Comment by kjellmf** [comment]
I ran into this error on windows and python 2.7:
``` python
Error
Traceback (most recent call last):
  File "D:\Python27\Lib\unittest\case.py", line 329, in run
    testMethod()
  File "D:\pydev\dot2tex\tests\test_dot2tex.py", line 18, in test_default
    source = dot2tex.dot2tex(testgraph)
  File "D:\pydev\dot2tex\dot2tex\__init__.py", line 62, in dot2tex
    return d2t.convert_graph(dotsource, **kwargs)
  File "D:\pydev\dot2tex\dot2tex\dot2tex.py", line 3103, in convert_graph
    tex = main(True, dotsource, options)
  File "D:\pydev\dot2tex\dot2tex\dot2tex.py", line 3053, in main
    s = conv.convert(dotdata)
  File "D:\pydev\dot2tex\dot2tex\dot2tex.py", line 773, in convert
    options=self.options.get('progoptions', ''))
  File "D:\pydev\dot2tex\dot2tex\dot2tex.py", line 201, in create_xdot
    p = Popen(cmd, shell=True, stdout=PIPE, stderr=PIPE, close_fds=True)
  File "D:\Python27\Lib\subprocess.py", line 667, in __init__
    raise ValueError("close_fds is not supported on Windows "
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr
```

I need to find a workaround for this.

**Comment by kjellmf** [comment]
I found a solution here: https://github.com/ipython/ipython/pull/4031/files

**Pull request merged**
